### ISSUE TITLE
Cannot go further the first iteration

### ISSUE THREAD

**Issue by Ipdorn** [lfares/remez-algorithm#1]
I don't know if the issue is on the solve sistem, on in the STEP 2 when you get the error function roots, Because i can plot the first iteration but then it gives me an Index Error on the Solve System

**Comment by lfares** [comment]
Can you put you error here? And did you change anything from the original algorithm, like the function or number of iterations?

**Comment by Ipdorn** [comment]
Here's the error
Traceback (most recent call last):
  File "C:/Users/xyz/PycharmProjects/remez/Run.py", line 39, in <module>
    b_vector, E = remez.solve_system(chebyshev_nodes, E)
  File "C:\Users\xyz\PycharmProjects\remez\Remez.py", line 32, in solve_system
    matrix_a[i].append((chebyshev_nodes[i] - self.a) ** j)
IndexError: list index out of range
